import {default as Blog} from './blog/Blog.jsx'
import {default as Features} from './features/Features.jsx'
import {default as Footer} from './footer/Footer.jsx'
import {default as Header} from './header/Header.jsx'
import {default as Possibility} from './possibility/Possibility.jsx'
import {default as WhatGP3} from './whatGP3/WhatGP3.jsx'